export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';
export const AUTH_LOG_IN = 'AUTH_LOG_IN';
export const AUTH_ERROR = 'AUTH_ERROR';
export const DATA_REQUEST_ERROR = 'DATA_REQUEST_ERROR';
export const DATA_REQUEST = 'DATA_REQUEST';
export const FILTER_SELECTED = 'FILTER_SELECTED';
